### ISSUE TITLE
units missing from Unit Dictionary

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#115]
---

Author Name: **Matt Jones** (Matt Jones)
Original Redmine Issue: 1000, https://projects.ecoinformatics.org/ecoinfo/issues/1000
Original Date: 2003-02-21
Original Assignee: Matt Jones

---

The following exellent email from Don Henshaw addresses a large number of
missing or problematic units in the unit dictionary.  We need to 1) fix these
and others that are identified, and 2) figure out how to release new versions of
the eml-unitdictionary without releasing new versions of EML.

---------------- Message from Don Henshaw ---------------------
David,
I have reviewed the Andrews unit dictionary.  The following are units of
measurement that we have used at the Andrews that I did not find in
eml-2.0.0\eml-unitDictionary.xml, as well as a few other notes. 
 
Thanks,
don
 
pressure: hectopascal (=100 pascals)
volume: cubic centimeters
volumetricArea: cubic meters per hectare               
volumetricArea: cubic meters per square meter
massDensity: megagrams per cubic meter
arealMassDensity: grams per square centimeter
arealMassDensity: megagrams per hectare
arealMassDensityRate: grams per square meter per day
amountOfSubstanceWeight: micromoles per gram
amountOfSubstanceWeightFlux: micromoles per gram per day
amountOfSubstanceWeightFlux: micromoles per gram per hour
amountOfSubstanceWeightFlux: nanomoles per gram per day
amountOfSubstanceWeightFlux: nanomoles per gram per hour
speed: inches per hour (used more as a rate than a speed)
energy?:  megajoule per square meter per day (solar radiation)
energy?:  langley (1 langley=4.187joules per square centimeter, 41870 joules per
square meter)
energy?: langleys per day (solar radiation)
conductance?: micro mhos per centimeter
 
I do not think there are unit types for the following (I assigned unit type names):
massPerMassRate: micrograms per gram per day
massPerMassRate: micrograms per gram per hour
massPerMassRate: micrograms per gram per week
massPerMassRate: nanograms per gram per hour
areaPerArea: square meters per hectare
luminanceRate??: micromoles per square meter per second (light measurement from
LICOR instrument)
 
Not sure how these fit:
milliequivalents per 100 grams
pH units
ppm (parts per million)
ppb (parts per billion)
 
What about the following use of degrees, minutes, seconds?
degrees azimuth
decimal degrees of latitude or longitude
degrees, minutes, seconds of latitude, longitude
 
On another topic:
Can a julian date be represented in the format string for measurementScale of
datetime i.e., YYYYddd
 
Other notes (being rather picky): pertaining to eml-unitDictionary.xml (2.0.0)
following units seems to show wrong abbreviation and multiplier
milliGramsPerMilliLiter
cubicMicrometersPerGram
 
The following unit names seem contrary to the convention of showing units in
singular form:
squareCentimeters
squareMillimeters
squareKilometers
cubicMeterPerKilogram
 
Not all units show an abbreviation, even when an obvious one exists, ie., kg/ha
or g/g liter shows "L" as the abbreviation

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Matt Jones** (Matt Jones)
Original Date: 2003-03-21T16:28:18Z

---

Scott Chapal submitted the following units as candidates as well:
---- Message from Scott Chapal ------
Working with our climate data, I found the need for:

kiloPascal
wattsPerMeterSquared
kiloJoulePerMeterSquared
Fuel Moisture % - percentWaterContentByWeight ??

Relative Humidity is presumably unitless?
---- End message -----

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Saurabh Garg** (Saurabh Garg)
Original Date: 2004-06-22T17:08:49Z

---


Regarding this bug in the last meeting, it was decided we may try to implement 
a registry where people can submit units and it will go through a review 
process after that. Should we aim to implement it for version 2.1.0?

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Matt Jones** (Matt Jones)
Original Date: 2004-09-02T16:38:15Z

---

Changing QA contact to the list for all current EML bugs so that people can
track what is happening.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:15:57Z

---

Original Bugzilla ID was 1000

**Comment by mobb** [comment]
added: 
cubic meter per hectare
cubic meters per square meter
megagrams per cubic meter
gram per square centimeter
gram per square meter per day
micromole per gram
micromole per gram per day
micromole per gram per hour
nanomole per gram per day
nanomole per gram per hour
inches per hour 
megajoule per square meter per day
langley 
langley per day

**Comment by mobb** [comment]
added some mass-specific rates
microgram per gram per day
microgram per gram per hour
microgram per gram per week
nanogram per gram per hour

area/area (forestry)
square meters per hectare

remaining units in this list were already present, or questions pertain to usage in quantities and measurements, not the unit itself.
