### ISSUE TITLE
missing or erroneous SI units in unitDictionary

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#139]
---

Author Name: **Margaret O'Brien** (Margaret O'Brien)
Original Redmine Issue: 1605, https://projects.ecoinformatics.org/ecoinfo/issues/1605
Original Date: 2004-06-16
Original Assignee: Matt Jones

---

1. The SI-derived unit "steradian" (sr) appears to be missing. it describes a
solid angle, and is the 3-dimensional equivalent of "radian". I dont believe it
can be described in terms of any other unit. 

2. the "waveNumber" unit is more correctly called reciprocalMeter (m-1), and
waveNumber is one of the measurements expressed by this unit (ie, waveNumber=the
number of wave cycles in 1 meter). Other measurements which are expressed in m-1
include absorbance, scattering and transmittance.

3. the unit "kilogramPerCubicMeter" is named inconsistently. It seems that it
should be plural, ie kilogramsPerCubicMeter. This is consistent with other unit
names (milligramsPerCubicMeter) and also how it is referenced as a ParentSI
attribute.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Matt Jones** (Matt Jones)
Original Date: 2004-06-22T19:53:36Z

---

Thanks for the comments.  I'm not sure that renaming units is a great idea
because it strands existing EML documents that use those units.  That said, your
comments do indicate a need for more consistent naming.  I'll target this at EML
2.1.0 and hope we can resolve these issues along with other 'units repository'
issues as partially described in bug 1000 and on the eml-dev mailing list archives.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Matt Jones** (Matt Jones)
Original Date: 2004-09-02T16:38:20Z

---

Changing QA contact to the list for all current EML bugs so that people can
track what is happening.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:17:40Z

---

Original Bugzilla ID was 1605

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Matt Jones** (Matt Jones)
Original Date: 2014-10-14T22:45:16Z

---

Status update:  The unit naming inconsistency described in this bug was not fixed in EML 2.1.1 in order to maintain backwards compatibility.  In general, we deemed that the names were not critical because they map to a precise STMML definition, so it is trivial to determine if two units are identical.  Therefore, we don't plan on removing units with names that deviate from the naming convention.  But there would be no harm in adding new units that are named following the conventions and provide a duplicate unit.  There hasn't been a major request for this yet.  Nor has there been a major need for additional units as people can define their own units in STMML.

**Comment by mobb** [comment]
done, deprecated
