### ISSUE TITLE
units not in eml-unitDictionary

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#140]
Author Name: **Margaret O'Brien** (Margaret O'Brien)
Original Redmine Issue: 1634, https://projects.ecoinformatics.org/ecoinfo/issues/1634
Original Date: 2004-07-09
Original Assignee: Matt Jones

As requested, here is the list of customUnits used by sbclter (to date).  The
current version of this list can be found at the url above.  Several of these
units need addional attributes or definition. These are commonly-used units in 
oceanography and limnology.
` 
<unit id="reciprocalMeter" name="reciprocalMeter" unitType="lengthReciprocal"
abbreviation="m-1" parentSI="meter" multiplerToSI="1">
<description>per meter, describes optical properties</description>
</unit>
`

`
<unit id="reciprocalMetersPerSteradian" name="reciprocalMetersPerSteradian"
unitType="lengthReciprocal" abbreviation="m-1*sr-1" parentSI="meter"
multiplerToSI="">
<description>describes directional optical measurements</description>
</unit>
`

`<unit id="microwattsPerSquareCentimeterPerNanometer"
name="microwattsPerSquareCentimeterPerNanometer" unitType="power" parentSI="joule">
<description>irradance unit</description>
</unit>`

`<unit id="microwattsPerSquareCentimeterPerNanometerPerSteradian"
name="microwattsPerSquareCentimeterPerNanometerPerSteradian" unitType="power"
parentSI="joule">
<description>directional irradiance unit</description>
</unit>
`

`
<unit id="microeinsteinsPerSquareMeterPerSecond"
name="microeinsteinsPerSquareMeterPerSecond" unitType="energy" parentSI="joule">
<description>
PAR irradiance unit, Seabird 911. 1Ein = energy of 1 mole photons
</description>
</unit>
`

`<unit id="microeinsteinsPerSquareCentimeterPerSecond"
name="microeinsteinsPerSquareCentimeterPerSecond" unitType="energy"
parentSI="joule">
<description>
PAR Scalar irradiance unit. 1Ein = energy of 1 mole photons
</description>
</unit>`

`<unit id="decibar" name="decibar" unitType="pressure" abbreviation="dbar"
parentSI="pascal" multiplerToSI="10,000">
<description>pressure, oceanography</description>
</unit>`

`<unit id="hectoPascal" name="hectoPascal" unitType="pressure" abbreviation="hPa"
parentSI="pascal" multiplerToSI="100">
<description>
SI unit for atmospheric pressure, equivalent in magnitude to millibar
</description>
</unit>`

`<unit id="percent" name="percent" unitType="massPerMass" abbreviation="o/o"
parentSI="gramsPerGram" multiplerToSI=".01">
<description>parts per hundred</description>
</unit>`

`<unit id="permil" name="permil" unitType="massPerMass" abbreviation="o/oo"
parentSI="gramsPerGram">
<description>
parts per thousand relative to a std  composition. UC-delta used for  isotope
enrichment = (Rx / Rs - 1) ·1000. o/oo used for salinity
</description>
</unit>`

`<unit id="sigma_unit" name="sigma_unit" unitType="massDensity"
parentSI="killogramsPerCubicMeter" constantToSI="-1000" multiplerToSI="1">
<description>seawater density = kg/m3 -1000</description>
</unit>`

`<unit id="millimolesPerCubicMeter" name="millimolesPerCubicMeter"
unitType="amountOfSubstanceConcentration" abbreviation="mmol*m-3"
parentSI="molesPerCubicMeter" multiplerToSI=".001">
<description>concentration unit</description>
</unit>`

`<unit id="micromolesPerLiter" name="micromolesPerLiter"
unitType="amountOfSubstanceConcentration" parentSI="molesPerCubicMeter"
multiplerToSI=".001">
<description>
concentration, same magnitude as micromolar (for a dissolved constituent)
</description>
</unit>`

`<unit id="microequivalentsPerLiter" name="microequivalentsPerLiter"
unitType="amountOfSubstanceConcentration" parentSI="molesPerCubicMeter"
multiplerToSI="">
<description>
concentration of charge (on dissolved ions). A single multiplier to SI is not
possible, since conversion includes valence of ion.
</description>
</unit>`

`<unit id="siemensPerMeter" name="siemensPerMeter" unitType="conductance"
abbreviation="S*m-1" parentSI="siemen" multiplerToSI="1">
<description>conductivity unit, seawater</description>
</unit>`

`<unit id="microsiemensPerCentimeter" name="microsiemensPerCentimeter"
unitType="conductance" parentSI="siemen" multiplerToSI=".0001">
<description>conductivity unit, freshwater</description>
</unit>`

`<unit id="milligramsPerSquareMeterPerDay" name="milligramsPerSquareMeterPerDay"
unitType="areaMassDensityRate" abbreviation="mg*m-2*d-1"
parentSI="kilogramsPerSquareMeterPerSecond" multiplerToSI="8.64E10">
<description>
areal primary production rate,  often in mg-Carbon for an integrated water column
</description>
</unit>`

`<unit id="kilogramsPerSquareMeterPerDay" name="kilogramsPerSquareMeterPerDay"
unitType="areaMassDensityRate" abbreviation="kg*m-2*d-1"
parentSI="kilogramsPerSquareMeterPerSecond" multiplerToSI="86400">
<description>
areal primary production rate, may be kg-DW, -Carbon or -nitrogen for kelp
</description>
</unit>`

`<unit id="milligramsPerCubicMeterPerDay" name="milligramsPerCubicMeterPerDay"
unitType="volumetricMassDensityRate" abbreviation="mg*m-3*d-1" parentSI=""
multiplerToSI="">
<description>
volumetric primary production rate, in a parcel of water
</description>
</unit>`

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Matt Jones** (Matt Jones)
Original Date: 2004-09-02T16:38:14Z

---

Changing QA contact to the list for all current EML bugs so that people can
track what is happening.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:17:45Z

---

Original Bugzilla ID was 1634

**Comment by mobb** [comment]
2018-06-28 line 1070
added inverseMeter, inverseCentimeter, deprecated waveNumber (in favor of inverseMeter)

**Comment by mobb** [comment]
Not adding: einsteins; recommendation is to use moles instead.

**Comment by mobb** [comment]
added 
- permil (analog to percent)
a few more concentration units:
- mmol per meter cubed 
- micro, milli and Equivalents per Liter (conductivity in water)

**Comment by mobb** [comment]
descriptions ok. closing. yay.
