### ISSUE TITLE
standardize namespace prefixed used for protocol module

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#230]
---

Author Name: **Margaret O'Brien** (Margaret O'Brien)
Original Redmine Issue: 3861, https://projects.ecoinformatics.org/ecoinfo/issues/3861
Original Date: 2009-03-05
Original Assignee: Matt Jones

---

Two different namespace prefixes have been used for the protocol module. These should be standardized. 

[mob@horcon eml]$ grep 'pro:' *xsd
eml-methods.xsd:          <xs:element name="protocol" type="pro:ProtocolType">
[mob@horcon eml]$ grep 'prot:' *xsd
eml.xsd:          <xs:element name="protocol" type="prot:ProtocolType">
[mob@horcon eml]$

Note that when this is fixed: in eml-documentation.xsl, the template name="externalNamespaceLink" should be edited to remove the namespace prefix that was dropped.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:24:47Z

---

Original Bugzilla ID was 3861

**Comment by earnaud** [comment]
Hello,
I am currently working with the .xsd files present in the EML git and also saw this issue. I do not understand why it has been closed. Will the issue be resolved in 2.2.0? 
Thanks by advance.
