### ISSUE TITLE
update documentation for species binomials

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#250]
---

Author Name: **Margaret O'Brien** (Margaret O'Brien)
Original Redmine Issue: 5704, https://projects.ecoinformatics.org/ecoinfo/issues/5704
Original Date: 2012-09-04
Original Assignee: Matt Jones

---

The EML documentation needs an update to reflect correct practice when including a taxonomic species name. Taxonomically speaking, the 'species name' is a genus and the specific epithet. But looking at it from a strictly hierarchical node structure the specific epithet looks and acts like the other nodes. However a node 'alterniflora' has no taxon rank by itself.

LTER already reccommends this construction in its Best Practices, but actual implementations are inconsistent, perhaps because of the normative documentation.

Another note: The normative docs also seem to refer to "Acer rubrum" as the 'common name' of Red Maple, which is incorrect.. 
 

Here is an example of 2 implementations sent to eml-dev (from Wade Sheldon):

with binomial:

<taxonomicClassification>
    <taxonRankName>Genus</taxonRankName>
    <taxonRankValue>Spartina</taxonRankValue>
    <taxonomicClassification>
       <taxonRankName>Species</taxonRankName>
       <taxonRankValue>Spartina alterniflora</taxonRankValue>
    </taxonomicClassification>
</taxonomicClassification>

without binomial:

<taxonomicClassification>
    <taxonRankName>Genus</taxonRankName>
    <taxonRankValue>Spartina</taxonRankValue>
    <taxonomicClassification>
       <taxonRankName>Species</taxonRankName>
       <taxonRankValue>alterniflora</taxonRankValue>
    </taxonomicClassification>
</taxonomicClassification>

Here is the text from the EML 2.1.1 normative docs:
(http://knb.ecoinformatics.org/software/eml/eml-2.1.1/eml-coverage.html)
seem to suggest the opposite approach:

"The name representing the taxonomic rank of the taxon being described.
The values included may be referenced from an authoritative source such
as the Integrated Taxonomic Information System (ITIS)in the U.S.
(http://www/itis.usda.gov) and in Canada
(http://sis.agr.gc.ca/pls/itisca/taxaget). Also, Species2000 is another
source of taxonomic information, found at (http://www.sp2000.org)
Example(s):
Acer would be an example of a genus rank value, and rubrum would be an
example of a species rank value, together indicating the common name of
red maple. It is recommended to start with Kingdom and include ranks
down to the most detailed level possible."

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:31:24Z

---

Original Bugzilla ID was 5704

**Comment by mobb** [comment]
The primary issue appears to have been already fixed. here is current text: 
``` <doc:example>'Acer' would be an example of a genus rank value, and
            'Acer rubrum' would be an example of a species rank value with the 
            common name of 'Red Maple'. </doc:example>```

I updated 2 things:
1.  added quotes and capitalization to the common name
2. removed the sentence from the example that recommended including all ranks. with the addition of external refs (issue #141), this is no longer necessary - in fact we might want to recommend the opposite.
