### ISSUE TITLE
unknown maintenanceUpdateFrequency

### ISSUE THREAD

**Issue by gastil** [NCEAS/eml#267]
Some eml docs have specified "unkown" instead of "unknown" for the maintenanceUpdateFrequency because there is a typo in the list of allowed values in eml-dataset.xsd. I suggest we retain the typo for backward compatibility, and add the corrected spelling. 
See for example knb-lter-mcr.7008.1

**Comment by mbjones** [comment]
Added 'unknown'.  Completed.
