### ISSUE TITLE
documentation for dateTime/formatString should comply with stds and good practice

### ISSUE THREAD

**Issue by mobb** [NCEAS/eml#268]
Documentation for dateTime formatStrings needs review and update. It should 
a) promote existing standards (ISO 8601), 
b) acknowledge common general practices

Examples should be justified, and dropped if they cannot be. one example needing close examination is the use of "Ws" to denote parts of month names.

**Comment by mobb** [comment]
The EDI date-time check working group will address this

**Comment by mobb** [comment]
EDI congruence checker WG will do this as part of their work on the date-time check

**Comment by mbjones** [comment]
Related to issue #248.
