### ISSUE TITLE
evaluate addition of referencePublication field

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#277]
Moving discussion on the need for a `referencePublication` field to its own ticket (it was raised by @cboettig in #259).

From #259, @cboettig writes:

> I still think this is an important issue, but difficult to implement satisfactorily because the whole idea is more of a practical hack than a technically precise idea. We struggled with this recently in codeMeta, and settled on a user's suggestion of referencePublication, codemeta/codemeta#144.

> In Dryad, the concept is well-defined and clearly advertised on every data page: "Please cite the following publication as well as the dataset", since all Dryad datasets must be associated with a unique publication. It's unclear how to define this connection in EML.

> In general, it seems this concept is a hack, best summarized as "please cite the following paper".

While there may be support for this proposal, it raises issues:

- the field is redundant with the citation info in eml-resource, and so it would be ambiguous as to how to resolve conflicts between the metadata in the document (e.g., list of creators, title, packageId), and what is found in the `referencePublication` field.  What if the order of authors are different, or the title differs?  Which is the truly recommended citation?
    - right now, recommended best practice is to construct citations from the EML metadata, using the format:
> Creator(s). pubDate. Title. Publisher. packageId.

- maybe this would be considered an *additional* reference that should be cited, in addition to the data set. This seems to be Dryad's practice.

If this were desired, I would consider an implementation such as:

```xml
<xs:element name="referencePublication" type="cit:CitationType" minOccurs="0" maxOccurs="unbounded">
  <xs:annotation>
    <xs:appinfo>
       <doc:tooltip>Reference Publication</doc:tooltip>
       <doc:summary>A citation to an additional publication that serves as an important reference for a dataset.</doc:summary>
       <doc:description>AA citation to an additional publication that serves as an important reference for a dataset. People using this dataset should generally cite the dataset itself (using the creator, pubDate, title, publisher, and packageId fields), and consider providing an additional citation to the Reference Publication.
       </doc:description>
    </xs:appinfo>
  </xs:annotation>
</xs:element>
```

**Comment by mobb** [comment]
referencePublication would work, if it’s intended to be used like ‘reference implementation’, i.e., the paper illustrates the usage of this dataset. 

For data papers, this would lead someone to the research paper that accompanied the dataset (if they reached the dataset by some pathway that did not include the paper) -- which is good - they are cases where they should be cited together. 

But I think it is too strong a statement to say that users should “consider citing the paper” too.  I can see plenty of cases where a reference publication are not be as tightly coupled as a research paper + data paper. ; 

The example has wording for both (doc:summary, doc:description)

```
<xs:element name="referencePublication" type="cit:CitationType" minOccurs="0" maxOccurs="unbounded">
  <xs:annotation>
    <xs:appinfo>
       <doc:tooltip>Reference Publication</doc:tooltip>
       <doc:summary>A citation to an additional publication that serves as an important reference for a dataset, and illustrates its use.</doc:summary>
       <doc:description>People using this dataset should generally cite the dataset itself (using the creator, pubDate, title, publisher, and packageId fields), but should be aware of this Reference Publication, as it may also be relevant to their work.
       </doc:description>
    </xs:appinfo>
  </xs:annotation>
</xs:element>

```

**Comment by mbjones** [comment]
See schema for final wording in sha 3beb10b.
