### ISSUE TITLE
documentation for eml_project incorrectly asserts that there must be a personnel with role "originator"

### ISSUE THREAD

**Issue by emilyodean** [NCEAS/eml#281]
The "personnel" subsection of the [eml-project](https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/./eml-project.html) documentation states that "A project must have at least one originator." This is inconsistent with the actual validation of the EML, which does require that each personnel have a "role" but does not require one of those personnel's roles to be "originator."

**Comment by mbjones** [comment]
Thanks, @emilyodean. Good catch on the language.  We need a way to state that each project must have at least one `personnel`, but that is awkward language wise.  I'll think about whatthe edit should be, but am open to suggestions.

**Comment by amoeba** [comment]
Why not just:

> The Personnel field extends ResponsibleParty with role information and is used to document people involved in a research project by providing contact information and their role in the project. ~A project must have at least one originator.~

**Comment by mbjones** [comment]
That sounds good.  Changes committed to 2.2 branch. Please review, otherwise this will go out with the 2.2. release.

**Comment by amoeba** [comment]
LGTM, thanks! Please close if that was enough of a review.

**Comment by mbjones** [comment]
I'll leave it open in the review state for a bit to see if others in the EML community have comments.  If not, then I'll close it as we prep for release.  Thanks.

**Comment by mobb** [comment]
my only comment is that this change looks fine. I agree, the original wording was awkward.
