### ISSUE TITLE
add license URL to EML

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#282]
EML currently supports a textual description of usage rights, but lacks a clear, machine-readable declaration of the license for a data set.  Consider adding an optional field for licenseURL or an SPDX license key that makes it simple for end users to be explicit about which license they follow.  See discussion in https://github.com/codemeta/codemeta/issues/67 .

**Comment by mbjones** [comment]
Added a new `license` element and `LicenseType`.  See SHA 491b715961cf7ffe931fce3237bfc6ccdff58687. And here's an example of it in use:

```xml
<licensed>
    <licenseName>Apache License 2.0</licenseName>
    <url>https://spdx.org/licenses/Apache-2.0.html</url>
    <identifier>Apache-2.0</identifier>
</licensed>
```

Note that the element is named `licensed` because the element name `license` was already in use in eml-software for the text of a software license.  I decided to leave the software elements in place for backwards compatibility.

**Comment by mbjones** [comment]
@cjones @jgoldstein @gothub @cboettig Please review for compatibility with the licensing needs for Arctic Data Center and with the CodeMeta licensing approach.  Thanks.

**Comment by csjx** [comment]
👍 This looks good to me. I reviewed the [Creative Commons embedding guide](https://labs.creativecommons.org/2011/ccrel-guide/) to see if we are in alignment.  Using RDFa it seems like they express the same information that we do between both the `usageRights` element and this `licensed` element.  They emphasize i18n of license descriptions, but that seems more to do with `usageRights` for EML. They also explicitly point to a license image, but I'm not too concerned about that. Ship it ™️ .

**Comment by LennertSchepers** [comment]
Hi, I believe that the example in the xsd (and [interactive schema](https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_licensed)) shows `<license>` instead of `<licensed>`. See https://github.com/NCEAS/eml/blob/fe77f8f9a34b08bc181857d1ad1240bcd99bead4/xsd/eml-resource.xsd#L388-L392

(in the _what's new in eml 2.2.0_ section on the website, the example is correctly mentioning `<licensed>`:  https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#dataset-license)

**Comment by mbjones** [comment]
Thank you for that report @LennertSchepers. It is indeed incorrect in the documentation, so I'll work on fixing that.
