### ISSUE TITLE
CitationType could accept other formats for biblio info

### ISSUE THREAD

**Issue by mobb** [NCEAS/eml#288]
adding this issue to record a couple of things:
1. the citation tree is a little cumbersome, especially when there are well-established formats for biblio data (like bibtex). maybe CitationType can be structured along the same lines as we are taking for TextType, with a choice of children. 

2. also see this choice of a full citation or simply and ID for a citation, per codemeta:
https://github.com/codemeta/codemeta/issues/144

**Comment by mbjones** [comment]
I agree.  And I have been thinking of incorporating bibtex blocks into the citations lists.  Probably as an alternative to the existing XML structure, but not a replacement.  I've been mentally thinking this over and thinking about both a new choice in the individual `citation` elements, and an additional `ReferenceList` type that allows a whole list of publications to be included in a bibtex block.  This also is a key part of the use of citation keys to reference citations in markdown blocks as implemented in #275.

**Comment by mbjones** [comment]
Added support for a `bibtex` element as an alternative to encoding citations in the EML XML structures.  Also added a `CitationListType` which is a list of citations for use in literature cited (#300) and related places.  Bibtex entries generally play well inside of XML structures, but XML escaping is still needed for many special characters, so consider embedding them in CDATA blocks if that makes it easier.
