### ISSUE TITLE
revisit STMML unitType

### ISSUE THREAD

**Issue by mobb** [NCEAS/eml#291]
in STMML unitType holds the dimensions of groups of units.  e.g., 
```
 <stmml:unitType id="volumetricRate" name="volumetricRate">
        <stmml:dimension name="length" power="3"/>
        <stmml:dimension name="time" power="-1"/>
    </stmml:unitType>
```
a unitType type is then reference to a unit with the unit/@unitType attribute. 
currently, some of the names for unitTypes are imprecise and/or wrong (e.g., rates called fluxes). A few look more like quantities than descriptions of dimensions, which is confusing (although they overlap). 

If we need a unitType for grouping elements, these should be revisited.

**Comment by mobb** [comment]
If EML 2.2 will have the conversions to SI, then this is high priority.
https://github.com/NCEAS/eml/issues/289#issuecomment-377397212

**Comment by mobb** [comment]
Example for unit kilogramPerMeterCubed. Currently, it gets assigned to the unitType "massDensity". The unitType column is one idea for unitTypes could be renamed, so that they describe the dimensions, rather than one of the possible quantities that unit could apply to.


Quantity name | Quantity Description | Example measurement | unitType | SI dimensions
-- | -- | -- | -- | --
massConcentration | a concentration is a mixture of two substances. The measurement will usually name them | Total particulate Carbon content, in sea water | massPerVolume | kilogram, power = 1; meter, power = -3
massDensity (or  more precisely, volumetric mass density) | mass per unit volume of a single substance | Density of fresh water 4 °C | massPerVolume | kilogram, power = 1; meter, power = -3

**Comment by mbjones** [comment]
@mobb Let's discuss this.  I am not following the distinction you are trying to make between quantity and unitType, especially when you say quantities are many:many with units but unitTypes are one:many.  In the [SI as described by NIST](https://www.nist.gov/pml/nist-guide-si-chapter-4-two-classes-si-units-and-si-prefixes), there are 7 `base quantities`, which can be combined into a much larger number of derived quantities.  These base quantities correspond to the `dimension` elements in STMML, and the `unitType` in STMML is a mechanism to define derived quantities that are combinations of the base quantities.  So, essentially, in an STMML `unitType` is the representation of a SI `quantity`, and they can be considered synonymous (and therefore 1:1).  I think unitTypes are what impart formal semantics onto the system in EML, and therefore are essential to the STMML model, and can not be removed without damage to the whole model.  While some of the names chosen for unitTypes could have been improved, their fundamental relationships to derived quantities were sound.  For backwards compatibility and semantic meaning, I think we need to maintain the original unitTypes.  It might be good to add some additional ones for naming consistency, but not at the expense of losing the originals.

**Comment by mobb** [comment]
It looks to me like there is no simple way to address this in STMML, mainly because of the one:many relationship between unitType and unit. unitType holds the SI parent dimensions, and with a few exceptions, these are correct, regardless of their names.  We have other projects (ECSO measurement ontology) where the relationships can be more flexible, so that is a better place to concentrate effort.

A few unitTypes have been called out as misapplying terms with generally accepted meanings, like "flux", and these have their own issues (#284, #285).  

There are many that I am not qualified to vet further, but if someone else with expertise in that science domain wants to do it, go right ahead! Please enter a specific issue for each one, and include the correction, per the examples above (e.g., #284).

removing the EML 2.2 milestone.

**Comment by maier-m** [comment]
One question I have and have conferred with @mobb is wether we can consider`unitType` and `parentSI` essentially equivalent. Scanning the old dictionary these essentially mapped 1 to 1 except for `volume` where confusingly the `parentSI` for `liter` is `cubicMeter` but for `cubicInch` it is `liter`. I think cleaning the `parentSI` and dropping `unitType` would be an excellent way to clean the unitDictionary for 2.2. The `parentSI` inherently contains all the dimensional information needed to understand the unit so I'm not sure the unitType is even necessary. 20% of the unitDictionary has never had a unitType so I wonder how many processes using EML rely on `unitType` anyways. `parentSI` should offer all the same information without the unneeded confusion with defining `unitTypes`.

**Comment by mobb** [comment]
Follow up: agree in principle with @maier-m, that parentSi has the dimensional info that is useful for grouping units. 

We will leave unitType as is, for backward compatibility (although if 20% of the list never had a unitType, it is inlikely that it was used much) W should discourage it's use, mainly because the 2.1 unitTypes sometimes contains a measurement quantity that is many:many with unit, and so incompatible with the way xml attributes must be applied (ie, only one instance allowed).

TO DO: ensure that parentSi content is complete and consistent.

**Comment by mobb** [comment]
related to #284, #285

**Comment by mobb** [comment]
parent SIs complete
