### ISSUE TITLE
cover cases where more than one unit applies to a column

### ISSUE THREAD

**Issue by mobb** [NCEAS/eml#292]
In string of pearls, the unit is usually in a separate field. People currently use "dimensionless"
suggestions include: 
varying
For use in tables where the the unit is an EML-attribute.
proposed definition: more than one unit

**Comment by mbjones** [comment]
In a name/value model, the unit of the value varies by row, and so typically people model these as name/value/unit columns. In that case, the 'unit' of all three columns would often be irrelevant as the column is typed as text, and any consumer would need to cast the value to the type associated with the named unit.  For example, I would argue that the three columns in the following example are all nominal:

| name | value | unit |
|-------|------|-----|
| length | 5      | cm |
| width | 6      | m |
| damage | high    | DamageType |
| diameter | 5.77 | cm |

The values for length, width, and diameter would need to be cast to numbers, which the value for damage would need to be cast to the DamageType.high value.

So, I would argue that the EML unit id should go in the `unit` column.

**Comment by mobb** [comment]
so could be a non-thing (you would not want to have ratios of values in that column). great.

**Comment by mobb** [comment]
this issue could be repurposed in a couple of ways. 
1. provide documentation for handling name/value tables (EDI has inherited some of this from LTER, and it's undergoing review)
2. feature request for EML to support name/value formats (e.g., streaming data). It would probably be another entity type. I thought there was an issue related to that way-back-when, but can't find it.
