### ISSUE TITLE
Generate an enumeration for the EML unit list, for eml-unitTypeDefinitions.xsd

### ISSUE THREAD

**Issue by mobb** [NCEAS/eml#302]

**Comment by mobb** [comment]
checked in.

**Comment by mbjones** [comment]
Looks like the xslt was added, but eml-unitTypeDefinitions.xsd was not yet updated.  Need to update that enumeration, and then review all units.

**Comment by mobb** [comment]
done https://github.com/NCEAS/eml/commit/eab57e9495524750b5444812818d59fd7570474b
