### ISSUE TITLE
The citation-* test files in the 2.2.0 testing suite still point to the 2.1.1 schema?

### ISSUE THREAD

**Issue by cboettig** [NCEAS/eml#304]
I'm not sure if this is really a problem or not, but I noticed that https://github.com/NCEAS/eml/tree/BRANCH_EML_2_2/src/test/resources, the citation-* files are still all pointing to the schema 2.1.1 schema.  Is that intentional?

**Comment by mbjones** [comment]
Just hadn't gotten there yet. I changed a few of the docs in the src/test/resources over to using the 2.2 namespace, but not all of them yet.  I'll add this ticket to the 2.2 milestone and flag it to be done.

**Comment by cboettig** [comment]
okay, cool.  Does the test suite include the bibtex-based citation styles too?  (Just started testing `emld` / `eml2` against 2.2.0 schema in https://github.com/cboettig/emld/tree/eml-2.2 and realized these were all still at 2.1.1)

**Comment by mbjones** [comment]
Updated namespace of all citation-test* docs in sha c494365 -- all seems to be working for now.
