### ISSUE TITLE
revise contributor list

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#309]
Consider contributors for the 2.2 release.  The main active contributors were jones, o'brien, mecum, maier, cjones, boettiger.  Maybe others that I missed...

**Comment by mobb** [comment]
add shild

**Comment by mbjones** [comment]
Add @twhitaker

**Comment by twhiteaker** [comment]
My info would be:
, Tim Whiteaker (whiteaker@utexas.edu)

**Comment by mbjones** [comment]
Need to add Steven Chong.
