### ISSUE TITLE
targeted examples of semantic annotation

### ISSUE THREAD

**Issue by mobb** [NCEAS/eml#314]
LTER IMC asked for 2 kinds of examples that include annotations to recommended vocabularies. 

- complete (EML record, as completely annotated as possible)
- XML fragments (easy to include in docs and BPs)
-

**Comment by amoeba** [comment]
Hey @mobb 	I saw the `needs-review` label on this so I thought I'd hop in.

By annotations, I assume you mean semantic annotation ala EML 2.2? What would a complete / completely annotated record look like? Or do you just mean a complete/valid EML doc? Either way, I think having a full EML 2.2 record as well as fragments is a great idea.

Folks have been working hard on carbon cycling / ECSO annotations so those'd be easy to get examples from. Though we generally stick to ecological examples with EML, I wonder if this wouldn't be a bad place to push EML a bit beyond ecology and have some geographic annotation examples (e.g. [GAZ](http://www.obofoundry.org/ontology/gaz.html)), or maybe look at how we'd annotate something from [BCO-DMO](https://www.bco-dmo.org/) (cruises, instruments, etc.).

**Comment by mobb** [comment]
thanks @amoeba. this was a hot topic at the LTER meeting last week; the sites are gung-ho. but need some recommendations and examples. 
Probably ECSO (complete measurements) are a good start at the attrib level, but the other locations need to be shown pretty quickly too (dataset-level, entity-level), which would most likely ref different vocabs. There was a lot of talk about keywords (and that dataset-level annotations could supplant keywords) -- eg, do we need both?  Probably we will want to phase this in, and outline a bunch of sub-tasks.

**Comment by amoeba** [comment]
Dataset-level annotations do kind of amount to dataset-level keywords, huh? Except more formal which is cool. We probably want to make it really clear for people when to do one or the other, or when to mix-and-match.

Are you planning on taking a first attempt at this?

**Comment by mobb** [comment]
I think task 1 is to figure out the characteristics of a "reliable vocabulary". then use those to come up with a list of candidate vocabs. EML-based repos will have to figure out how to deal with each one of these.

**Comment by mbjones** [comment]
TODO:

- clean up examples, and add a MeasurementType example in eml-sample.xml
- decide whether to eliminate eml-semantics.xml, or expand it

**Comment by stevenchong** [comment]
I can add in a MeasurementType example to the eml-sample.xml doc

**Comment by mbjones** [comment]
@stevenchong @mobb Are these examples now complete in the primer document?

**Comment by stevenchong** [comment]
The examples in the primer are complete. Some came from the eml-sample doc
and some did not.

**Comment by mbjones** [comment]
Great, thanks.  Then I am closing this issue.  But I'm leaving #320 open for final review (I think I saw a few notes to self in there still).
