### ISSUE TITLE
create sem annotation primer

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#320]
Need a chapter in the spec on how to properly use the new eml-semantics module `annotation` tag.

**Comment by mobb** [comment]
obviates #314

**Comment by mobb** [comment]
Primer is getting long. Suggest pulling out some of the background bits into the FAQs.

**Comment by mobb** [comment]
Received these actual Q's so far:
1. What does ‘dereferenced’ mean?  (context: a URI in an annotation)
2. Explain the difference between an URI and a URL. (context: sample URIs look a lot like a URL.  What makes it a URI?)
3. review in this section below (“When are ID’s required in the EML”) - context: annotations
4. An example of a controlled vocabulary with a rdfs label or skos label would be helpful here in this text about labels.  
5. What is SKOS,
6. what is RDFS?
7. RDF Graph: a computer can’t parse this graph.  What does the RDF look like?
8. Are there tools are available to help data managers select subjects, predicates, and objects to annotate with?

**Comment by mbjones** [comment]
The primer has been drafted.  Moving to Review for final review.

**Comment by mobb** [comment]
IMO, ready for eml 2.2. additions/changes should have their own issues; please include "annotation primer" and tag with "documentation'
