### ISSUE TITLE
Typo in spatialReference.xsd referencing 

### ISSUE THREAD

**Issue by amoeba** [NCEAS/eml#326]
@jeanetteclark noticed this today on Slack: There's a typo (wrong extension) in `eml/spatialReference.xsd` in a reference to the `eml-spatialReferenceDictionary.xml` file:

https://github.com/NCEAS/eml/blob/4417cbf6588fdca4e06bd67190a9d7a18a8e944f/eml-spatialReference.xsd#L91-L93

`eml-spatialReferenceDictionary.xsl` should be `eml-spatialReferenceDictionary.xml`

I'll hold off on changing this since the docs are in flux for the EML 2.2 release.

**Comment by mbjones** [comment]
OK, I fixed this in the 2.2 branch schema file, and it will now be included in the release with the right name.

I don't know how to provide a link, as the schemas are used to generate docs in many contexts, some online, some not, and we have no knowledge of the html files that might be generated from these source files. Suggestions welcome, but for now I am not planning on adding a link.

**Comment by amoeba** [comment]
Thanks, @mbjones, that's probably good enough. I'm okay with this Issue getting closed now. I don't have any suggestions for linkifying the reference in the in-schema docs.
