### ISSUE TITLE
Fill in annotation for EML methods in its schema

### ISSUE THREAD

**Issue by amoeba** [NCEAS/eml#330]
Found this today while spelunking around:

https://github.com/NCEAS/eml/blob/dd6659f741fc6b9cbd29ad4e80dd084454207404/xsd/eml-methods.xsd#L73-L77

This should get filled or removed. `methodStep` has some text that I think pertains to both `methods` and itself, so I think this could get split between the annotations for `methods` and `methodsStep`:

https://github.com/NCEAS/eml/blob/dd6659f741fc6b9cbd29ad4e80dd084454207404/xsd/eml-methods.xsd#L80-L94

Anyone wanna have a go?

**Comment by mobb** [comment]
see commit 913cbbb261ad30439b6e96031a68b1650e7d497c
