### ISSUE TITLE
creating attribute IDs for semantic annotations

### ISSUE THREAD

**Issue by stevenchong** [NCEAS/eml#332]
I'm working on the semantic annotation of attribute elements in the ADC.  The annotated attribute elements will each need an `id` attribute to validate.  Are there any recommendations for how to format the IDs?  

The `id` will be used to construct the subject URI for the triple.  See here for a related comment: https://github.com/NCEAS/eml/issues/25#issuecomment-407931771

One suggestion I received was to use the entity and attribute positions (e.g. `ent1_att3`).  However, I'm carrying over annotations if a data package gets updated (i.e. the annotations from an older package version get transferred over to the newest version) and this might lead to some confusion if the order of entities or order of attributes were to change.

Another idea was to use a combination of entity and attribute names for the `id`, but there will be issues like whitespaces, special characters, etc.

I wanted to check if there are any preferences, best practices or conventions to follow.

**Comment by mobb** [comment]
that suggestion (using position) probably only works for a one-time effort. For anything that is likely to receive an update its best to involve the original curator. From the EDI/LTER pov, this is one reason we want to promote annotation at origin -- IDs are the submitter's responsibility. Should we involve the ADC curators in this activity?

That said, a combination of entity-attribute names might be safe - but actually making it safe is painful.  EML (alone) does not require that entity and att names are unique, so even after removing whitespace and special characters there is no guarantee - you'd have to do some other checking or processing.

**Comment by amoeba** [comment]
After a lively discussion on Slack, I think I don't really care if you use any of `att{n}`, `ent{n}_att{m}`, or a random string. I think numeric ordering is tricky enough that it might be worth avoiding. And I think trying to encode a ton of semantics into the IDs in this effort is too much work so something opaque or semi-opaque would work. Maybe decide based upon what's easiest for you in your annotation effort and go from there.

**Comment by csjx** [comment]
Yes, I'd agree that opaque or semi-opaque ids would be best too.  Our discussion of using 30-character random alpha-numeric strings would work, and is probably overkill.  I'd expect 5 or 10 character random strings would be fine too.

**Comment by csjx** [comment]
Actually, 5 factorial is 120, whereas 10 factorial is 3,628,800, so 10 or higher is probably best to avoid collisions.

**Comment by amoeba** [comment]
The first four bytes of a v4 UUID have pretty low collision. I just generated 1 million of them and only had 127 collisions.

```
> strsplit(uuid::UUIDgenerate(), "-")[[1]][1]
[1] "5a98f11a"
```

**Comment by stevenchong** [comment]
Thanks to all who replied.  The general opinion has been leaning towards random identifiers, so I'll go ahead and use a random 10-character string for the attribute IDs (that don't already have IDs).  I will close this issue.
