### ISSUE TITLE
split eml-semantic-faq from eml-faq?

### ISSUE THREAD

**Issue by mpsaloha** [NCEAS/eml#339]
It may be useful to separate the semantic portions of the eml-faq as a separate document, since these are largely addressing general questions about the semantic web and linked data

**Comment by amoeba** [comment]
Sounds reasonable to me.

**Comment by stevenchong** [comment]
I agree.  Readers of the semantic annotation primer would have to scroll down the FAQ to find relevant information, otherwise.

**Comment by mobb** [comment]
the semantic FAQs are in the semantics primer.
