### ISSUE TITLE
final EML 2.2 documentation cleanup

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#340]
- [x] Create and configure domain name for https://eml.ecoinformatics.org
- [x] Decide where the validation service will run, and set it up
    - Fix link in section 9.4 to the parser
- [x] Review ecoinfo charter and governance language in README
- [x] Discuss deprecating the eml-access module
- [x] Issue a DOI and update README
- [x] Add bibtex citation for copying
- [x] Create much simpler intro to semantic annotations, with human readable language
- [x] Fix footnote language in 10.6 sem-primer
- [x] Update release notes in section 12
- [x] Update contributors to include Chong
- [x] Embed links to schema docs in book
- [x] add a CodeMeta.json file describing the release
- [x] determine if we can eliminate com.oreilly.servlet and its LICENSE restrictions

**Comment by mobb** [comment]
semantic primer  TO DOs:
1. add section numbers (letters?) 
 - A. Introduction
 - B. Semantics annotations in EML 2.2
 - C. Appendix
A reader should be able to create an EML annotation with examples, etc in section B alone (which currently is about half the total pages). Section C is for more in-depth info if they want it. 

2. It should also be obvious to readers that they will need to have some external vocabs recommended. We have not come out and said that anywhere. nor have we started on a list recommendations, except de facto (in examples). My current feeling is that we add our example onts to the glossary (or appendix sub-section titled "Vocabs in examples"), but save formal  recommendations for a separate doc. 

3. enhance sub-section "organization of this doc" . describe A, B, C sections.

4. In each example's intro paragraph, use a list to highlight the three parts of the semantic statement. move parentheticals about external vocabs to appendix

5. introduce the "semantic statement" (plain english, no tech) right after the first code block showing an annotation node (on p2). link to below (addresses SC's comment).

6. add these terms to glossary (or other appendix section), link in text as much as possible: 

- [ ] knowledge graph
- [ ] controlled vocabulary
- [ ] dereference
- [ ] subclass
- [ ] semantic statement
- [ ] Information Artifact Ontology (or section titled vocabs in examples)
- [ ] Envo (or section titled vocabs in examples)

**Comment by stevenchong** [comment]
More semantic primer to do's:

- [ ] Example 4, line 239: add text for `annotations` annotation example (@mobb )
- [ ] fix the adam.shepherd example and replace it with a real person from Cedar Creek (line 270 and also to Examples 1, 4, 5 and the second RDF graph)  (@stevenchong )
- [ ] look into putting URIs into the `id` attributes or use them with `<annotations references ="">`. (@mpsaloha ) Also need to edit the primer text and related examples.  This is related to #143

**Comment by mbjones** [comment]
Updated release notes.

**Comment by mbjones** [comment]
Removed the validation service links from the docs.  Much easier to run the validation class locally.

**Comment by mbjones** [comment]
Deprecated the eml-access module in the docs, discouraging use of the `access` elements.  See sha 24301e3b94c29c2152d81553e5d6153d74629949.

**Comment by mbjones** [comment]
Updated README and contributors doc to remove language about the ecoinformatics charter, and instead just refer to maintainers for decisions.  See sha 15999974.

**Comment by mbjones** [comment]
Added a codemeta.json file and a 'Copy Bibtex' button in sha 5f3fccd9.
