### ISSUE TITLE
change namespaces to use https

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#341]
Current eml namespaces use a custom URI that starts with `eml://`, such as `eml://ecoinformatics.org/eml-2.1.1` and `eml://ecoinformatics.org/eml-dataset-2.1.1`.  Because these are not registered URIs, and because some people prefer https URIs (even if they are just names that don't necessarily resolve), a request has been made to switch to this convention. 

## Proposal

New namespaces for EML 2.2.0 would have the form:

- `https://eml.ecoinformatics.org/eml-2.2.0`
- `https://eml.ecoinformatics.org/eml-dataset-2.2.0`
- `https://eml.ecoinformatics.org/eml-resource-2.2.0`
- etc.

Software (Metacat, MetacatUI, XSLT, etc) will need to be updated to recognize this new namespace format.

Comments appreciated.

**Comment by mobb** [comment]
EDI has been testing the EML 2.2 changes as they progress, and would like to test this one too. So go ahead and push the namespace change, and we will test again. Probably there is no objection.

**Comment by mbjones** [comment]
New namespace names were implemented as proposed (`https://eml.ecoinformatics.org/eml-2.2.0`).  The internal ant tests are passing.  Need to test and make code changes for the following:

- [ ] Metacat (@taojing2002 and @amoeba )
- [ ] MetacatUI (@laurenwalker)
- [ ] XSLT in Metacat (@taojing2002)

**Comment by amoeba** [comment]
I've just finished testing the DataONE indexing stack, Metacat, and MetacatUI (sans editor) with the new namespace change and things look good. I'm awaiting reviews on PRs but hope I can get comments by next week and @taojing2002 	can help me do some testing. An example EML 2.2.0 doc can be see on https://neutral-cat.nceas.ucsb.edu/.

**Comment by mbjones** [comment]
Awesome, thanks @amoeba!

**Comment by luciaV86** [comment]
Hi,
I am working on an XSL Transformation to allow a mapping from EML2.1.1 to EML2.2.0 but I have an issue with the namespace declaration, an issue that arises also for the transformation that @mbjones has developed (https://github.com/NCEAS/eml/blob/main/style/eml211to220.xsl).

Given for example as input an XML file that starts with:
_<eml:eml 
	xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd" 
	packageId="xxx" 
	system=“xxx” xml:lang="en">
	<dataset>
		….._

<eml:eml packageId="edi.1073.1" system="https://pasta.edirepository.org" 
xsi:schemaLocation="https://eml.ecoinformatics.org/eml-2.2.0 https://nis.lternet.edu/schemas/EML/eml-2.2.0/xsd/eml.xsd">

I have the following error: “Namespace prefix eml on eml is not defined in Entity”

I have tried with different EML2.1.1 files from different sources but the result is always the same.

If I add the following two lines to the input file:
	_xmlns:eml="https://eml.ecoinformatics.org/eml-2.2.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"_

and hence the file becomes:
_<eml:eml 
	xmlns:eml="https://eml.ecoinformatics.org/eml-2.2.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	
	xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd" 
	packageId="eml.1.1" 
	system=“xxx” xml:lang="en">
	<dataset>
		….._

the transformation works fine and gives the desired output, but I cannot modify the input files that I will use as harvesting source.
How did you managed this when testing your transformation?

Thank you very much in advance!

**Comment by mbjones** [comment]
@luciaV86 Let's open this in a new ticket, as it is unrelated to this topic in this closed issue #341. I copied your thread across to a new ticket #383 and will address your question there.
