### ISSUE TITLE
Clicking on documentation website copies the BibTeX example to the clipboard

### ISSUE THREAD

**Issue by twhiteaker** [NCEAS/eml#350]
On the [documentation website](https://eml.ecoinformatics.org), when I click the Search button, or in the search box, or in the body text of the page, it moves focus to a location just after the Copy BibTeX button and replaces what's in my Windows clipboard with the following text:

@article{EML_2019,title={Ecological Metadata Language version 2.2.0},url={https://eml.ecoinformatics.org},DOI={10.5063/f11834t2},publisher={KNB Data Repository},author={Jones, Matthew and O’Brien, Margaret and Mecum, Bryce and Boettiger, Carl and Schildhauer, Mark and Maier, Mitchell and Whiteaker, Timothy and Earl, Stevan and Chong, Steven},year={2019}}

Copying the text is what should happen when you click the Copy BibTeX button on the page. However, it's as if the event handler listening for the Copy BibTeX button to be clicked, is actually listening for any part of the page to be clicked.  This has these undesired effects when clicking on places besides the Copy BibTeX button:
1. Unwanted text is copied to the clipboard.
2. Search functionality is hampered. I cannot click the search box to enter a search term because focus is immediately taken away from it and placed just after the Copy BibTeX button (click the search box, and then press Shift+Tab to see the button get focus).

Note that I can still successfully enter and stay within the Search box if I use the Tab key.

To reproduce the issue:
1. Put some text in your Windows clipboard, like "Hello World."
2. Browse to https://eml.ecoinformatics.org.
3. Click the Search button (magnifying glass icon) at the top.
4. Paste the contents of your clipboard somewhere other than the current page. 
5. Click in the Search box. Focus is immediately lost.

**Comment by mbjones** [comment]
Good catch, @twhiteaker .  The handler for the bibtext button is too broad, and needs to be fixed. PRs would be welcome!

**Comment by amoeba** [comment]
Reviewed and tested the change. Much appreciated @twhiteaker !
