### ISSUE TITLE
broken link in eml documentation

### ISSUE THREAD

**Issue by srearl** [NCEAS/eml#364]
Hi @amoeba - Seeing the spelling error fix that Steven noted reminded me that there is a broken link in the eml docs. In the following section of `eml-220info.md`, the link should refer to: `semantic-annotation-primer.html`. Seemed overkill for a PR. Odd that I was not able to reference a specific line number of that file, sorry about that. S

```
## Supporting Semantic Metadata

See the [EML Semantic Annotation Primer](eml-semantic-annotations-primer.html) 
for a thorough overview. In brief, EML 2.2.0 supports entering terms from an 
ontology via `<annotation>` elements to precisely describe items such as data 
attributes/variables, datasets, and people.  Annotations are allowed in five 
locations in the EML document:
```

**Comment by amoeba** [comment]
no worries and thanks for the report @srearl! I'll take a look and get a fix in.

**Comment by amoeba** [comment]
Fixed push up on our in-development branch and will be reflected online in the future.

Thanks again @stevenchong and @srearl
