### ISSUE TITLE
Rename the master branch to main

### ISSUE THREAD

**Issue by csjx** [NCEAS/eml#365]
From an inclusivity perspective, I suggest we rename the `master` branch to `main` and generally use more welcoming terms as we describe our software architectures. The use of the the terms `master` and `slave` in computing are not welcoming.  For context, see the [Inclusive Naming](https://inclusivenaming.org) project and [this repo](https://github.com/github/renaming).

**Comment by mbjones** [comment]
Renamed master to `main`, and synced all work.  Local copies can be updated with the new branch name with:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
