### ISSUE TITLE
eml211to220.xsl errors

### ISSUE THREAD

**Issue by mbjones** [NCEAS/eml#383]
Ticket submitted by @luciaV86, copied from issue #341:

Hi,
I am working on an XSL Transformation to allow a mapping from EML2.1.1 to EML2.2.0 but I have an issue with the namespace declaration, an issue that arises also for the transformation that @mbjones has developed (https://github.com/NCEAS/eml/blob/main/style/eml211to220.xsl).

Given for example as input an XML file that starts with:
_<eml:eml 
	xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd" 
	packageId="xxx" 
	system=“xxx” xml:lang="en">
	<dataset>
		….._

<eml:eml packageId="edi.1073.1" system="https://pasta.edirepository.org" 
xsi:schemaLocation="https://eml.ecoinformatics.org/eml-2.2.0 https://nis.lternet.edu/schemas/EML/eml-2.2.0/xsd/eml.xsd">

I have the following error: “Namespace prefix eml on eml is not defined in Entity”

I have tried with different EML2.1.1 files from different sources but the result is always the same.

If I add the following two lines to the input file:
	_xmlns:eml="https://eml.ecoinformatics.org/eml-2.2.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"_

and hence the file becomes:
_<eml:eml 
	xmlns:eml="https://eml.ecoinformatics.org/eml-2.2.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	
	xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd" 
	packageId="eml.1.1" 
	system=“xxx” xml:lang="en">
	<dataset>
		….._

the transformation works fine and gives the desired output, but I cannot modify the input files that I will use as harvesting source.
How did you managed this when testing your transformation?

Thank you very much in advance!

**Comment by mbjones** [comment]
@luciaV86 -- thanks for the report. Can you describe exactly how you ran the transformation and found this issue? I can't seem to replicate the behavior you are seeing. As an example, I use the `xmlstarlet` package from the commandline to run the XSLT transform, and I ran it against a EML 2.1.1 document in the EML repository: https://github.com/NCEAS/eml/blob/main/src/test/resources/sampleLTERIntellectualRights.xml  When I run the transform, it produces the correct result. The header of that starting file seems to be the same namespace as yours:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Corinna Gries (private) -->
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" xmlns:cit="eml://ecoinformatics.org/literature-2.1.1" xmlns:doc="eml://ecoinformatics.org/documentation-2.1.1" xmlns:ds="eml://ecoinformatics.org/dataset-2.1.1" xmlns:prot="eml://ecoinformatics.org/protocol-2.1.1" xmlns:res="eml://ecoinformatics.org/resource-2.1.1" xmlns:sw="eml://ecoinformatics.org/software-2.1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1
http://ces.asu.edu/eml/eml.xsd" packageId="tempid" system="ces_dataset">
```

Here's the command I ran (from the root of the EML repository folder):

`xml tr style/eml211to220.xsl src/test/resources/sampleLTERIntellectualRights.xml > out.xml`

The `out.xml` file that it produces has the correct EML 2.2.0 namespace:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<eml:eml xmlns:eml="https://eml.ecoinformatics.org/eml-2.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://eml.ecoinformatics.org/eml-2.2.0 http://ces.asu.edu/eml/eml.xsd" packageId="tempid" system="ces_dataset">
```

I also ran the same thing with the `xalan` XSLT processor and got the same result. A reproducible example would be very helpful. Could you submit the full EML document that is failing for you to this ticket? Thanks.

**Comment by luciaV86** [comment]
@mbjones -- thank you very much for your kind and fast answer.
Yes, your EML2.1.1 document works fine also for me, but the header is different, that's the reason.
Your header:
```
<eml:eml 
xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" 
xmlns:cit="eml://ecoinformatics.org/literature-2.1.1" 
xmlns:doc="eml://ecoinformatics.org/documentation-2.1.1" 
xmlns:ds="eml://ecoinformatics.org/dataset-2.1.1" 
xmlns:prot="eml://ecoinformatics.org/protocol-2.1.1" 
xmlns:res="eml://ecoinformatics.org/resource-2.1.1" 
xmlns:sw="eml://ecoinformatics.org/software-2.1.1" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://ces.asu.edu/eml/eml.xsd" 
packageId="tempid" system="ces_dataset">
```

My header:
```
<eml:eml 
xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 http://rs.gbif.org/schema/eml-gbif-profile/1.1/eml.xsd"
         packageId="xxx" 
         system="xxx" 
         xml:lang="en">
```

Indeed, it not includes the `xmlns:eml` and `xmlns:xsi` that are needed to run the XSLT.

However, I have discovered the main reason behind the issue and I am reporting it here since it can help someone else.
Let consider as example the following EML2.1.1 document that is published on DataONE: https://cn.dataone.org/cn/v2/object/doi:10.18739%2FA2K06X129.
In the **Firefox** browser the header is not correctly showed, only xsi:schemaLocation and packageId + system attributes are shown... and this can be due to several installed add-ons.
A simple copy & paste of this XML code in order to have an input for the XSL Transformation replicates the behavior that I had.
On the contrary, by using other 3 ways the complete XML is shown and everything works fine:
- use the Firefox browser with the View Page Source option (available when you right click on the page);
- use the Chrome browser (the full XML is directly shown);
- save the page as xml doc.

**Comment by mbjones** [comment]
Thanks for the clarification, @luciaV86 . What you describe now makes sense, and I think is what should happen. The definition of the `eml` namespace is very much required in a valid EML document, and the XSLT transformation will fail if the document is invalid (especially of the namespace of the root element is not defined). Your explanation of how you downloaded the docs makes it clear -- I'd say the best way to download and save a document in its original form is using a commandline browser (e.g., curl) or by using the `Save` function from your browser. Once you download an EML document, you can check whether it is valid or not -- and if not, I would expect that XSLT transforms will fail on it. Several validators are available, including the [online validator](https://knb.ecoinformatics.org/emlparser/) and others described in the spec: https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#validity-of-new-eml-2.2.0-documents 

I'm going to close this issue as I don't think there are any issues here, but feel free to reopen it or just continue the conversation if you have more to discuss. Thanks.
